export const sample_foods = [
    {
        id:'1',
        name: 'Vegetable Pizza',
        cookTime: '10-20',
        price: 12,
        favorite: false,
        origins: ['india'],
        stars: 4.5,
        imageUrl: 'pizza_1.png',
        tags: ['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name: 'Meatball',
        cookTime: '20-30',
        price: 20,
        favorite: true,
        origins: ['persia','china','russia'],
        stars: 5,
        imageUrl: 'bool_2.png',
        tags: ['SlowFood','Lunch'],
    },
    {
        id:'3',
        name: 'Hamburger',
        cookTime: '10-15',
        price: 8,
        favorite: false,
        origins: ['germany','us'],
        stars: 3.5,
        imageUrl: 'burger_3.png',
        tags: ['FastFood','Hamburger'],
    },
    {
        id:'4',
        name: 'French Fries',
        cookTime: '5-10',
        price: 5,
        favorite: true,
        origins: ['france'],
        stars: 4,
        imageUrl: 'french_fries_4.png',
        tags: ['FastFood','fry'],
    },
    {
        id:'5',
        name: 'Vegetable Soup',
        cookTime: '4-10',
        price: 4,
        favorite: false,
        origins: ['india','asia'],
        stars: 3,
        imageUrl: 'soup_5.png',
        tags: ['SlowFood','Soup'],
    },
    {
        id:'6',
        name: 'Dosa',
        cookTime: '10-15',
        price: 8,
        favorite: true,
        origins: ['india'],
        stars: 4,
        imageUrl: 'dosa_6.png',
        tags: ['FastFood','dosa'],
    },
    {
        id:'7',
        name: 'Chese_corn_pizza',
        cookTime: '12-18',
        price: 18,
        favorite: true,
        origins: ['india','us','asia'],
        stars: 5,
        imageUrl: 'Chese_pizza.png',
        tags: ['FastFood','Lunch','Pizza'],
    },
    {
        id:'8',
        name: 'Veg_Manchurian',
        cookTime: '8-10',
        price: 10,
        favorite: true,
        origins: ['india','china','asia'],
        stars: 3.5,
        imageUrl: 'Manchurian.png',
        tags: ['SlowFood','Lunch'],
    }
];

export const sample_tags = [
    { name: 'All',count:8 },
    { name: 'FastFood',count:5 },
    { name: 'Pizza',count:2 },
    { name: 'Lunch',count:3 },
    { name: 'SlowFood',count:3 },
    { name: 'Hamburger',count:1 },
    { name: 'fry',count:1 },
    { name: 'Soup',count:1 },
];

export const sample_users = [
    {
      id: 1,
      name: 'Bhavishya Patidar',
      email: 'bhavishyapatidar2022@gmail.com',
      password: '12345',
      address: 'indore,india',
      isAdmin: true,
    },
    {
      id: 2,
      name: 'Amit patidar',
      email: 'amitpatidar@gmail.com',
      password: '12345',
      address: 'bhopal,mp',
      isAdmin: false,
    },
  ];
  